Id: RITE.VEXOTControl
Name: VEXOTControl
Publisher: RITE
Version: 1.10.50
License: Proprietary
LicenseUrl: https://www.gnu.org/licenses/gpl-3.0.txt
Installers: 
    - Arch: x64
      InstallerType: exe
      Url: https://github.com/AndreiBee/VEXOTControl/releases/download/v1.10.50/VEXOTControlInstaller_v1.10.50.exe
      Sha256: 7B690E2BBC51DB0DE4E67168FDBE4B21BA1705B8AA4065C0FC1B7753704265BD
      Switches:
        Silent: /SILENT
        SilentWithProgress: /SILENT
Description: VEXOTControl is a tool for controlling KETEK device.
Homepage: https://github.com/AndreiBee/VEXOTControl
